select (select value from meta where key = 'root') as root,
       cast((select value from meta where key = 'schema_version') as integer) as schema_version,
       (select value from meta where key = 'file_source') as file_source,
       (select value from meta where key = 'indexed_at') as indexed_at,
       (select value from meta where key = 'updated_at') as updated_at,
       (select value from meta where key = 'last_operation') as last_operation,
       (select value from meta where key = 'vcs_kind') as vcs_kind,
       (select value from meta where key = 'vcs_revision') as vcs_revision,
       (select value from meta where key = 'vcs_ref') as vcs_ref,
       (select value from meta where key = 'vcs_head') as vcs_head,
       (select value from meta where key = 'vcs_branch') as vcs_branch,
       cast((select value from meta where key = 'vcs_dirty') as integer) as vcs_dirty,
       (select count(*) from files) as files,
       (select count(*) from symbols) as symbols,
       (select count(*) from lines) as lines,
       (select coalesce(sum(code_lines), 0) from file_metrics) as code_lines,
       (select coalesce(sum(comment_lines), 0) from file_metrics) as comment_lines,
       (select coalesce(sum(blank_lines), 0) from file_metrics) as blank_lines,
       (select value from meta where key = 'hash_algorithm') as hash_algorithm,
       cast((select value from meta where key = 'fts5') as integer) as fts5;
